# Generated by Django 3.1.7 on 2021-04-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210406_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
