# Generated by Django 3.1.7 on 2021-04-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('computer', models.BooleanField(default=False)),
            ],
        ),
    ]
